a

diff --git a/CPP08_working/Hoach/ex02/Makefile b/CPP08_working/Hoach/ex02/Makefile
--- a/CPP08_working/Hoach/ex02/Makefile
+++ b/CPP08_working/Hoach/ex02/Makefile
@@ -1,192 +1,76 @@
-include Settings.mk
-include Colours.mk
+# **************************************************************************** #
+#                                                                              #
+#                                                         :::      ::::::::    #
+#    Makefile                                           :+:      :+:    :+:    #
+#                                                     +:+ +:+         +:+      #
+#    By: honguyen <honguyen@student.42.fr>          +#+  +:+       +#+         #
+#                                                 +#+#+#+#+#+   +#+            #
+#    Created: 2024/11/10 13:54:54 by honguyen          #+#    #+#              #
+#    Updated: 2025/05/01 21:19:01 by honguyen         ###   ########.fr        #
+#                                                                              #
+# **************************************************************************** #
 
-#------------------------------------------------------------------------------#
-#                                   GENERICS                                   #
-#------------------------------------------------------------------------------#
+NAME		= ex00
+CXX			= c++
+CXXFLAGS	= -Wall -Wextra -Werror -std=c++98
+RM			= rm -f
 
-# Special variables
-DEFAULT_GOAL: all
-.DELETE_ON_ERROR: $(NAME)
-.PHONY: all long \
-		clean clear \
-		fclean fclear \
-		re run rerun \
-		leaks releaks \
-		vleaks revleaks \
-		norm libft \
-		brew cmake \
-		grind \
+SRCS_DIR 	= srcs
+SRCS		= $(addprefix $(SRCS_DIR)/, main.cpp)
 
+OBJS_DIR	= objs
+OBJS		= $(addprefix $(OBJS_DIR)/, $(notdir $(SRCS:.cpp=.o)))
 
-#------------------------------------------------------------------------------#
-#                                  VARIABLES                                   #
-#------------------------------------------------------------------------------#
+INCS_DIR	= incl
+INCS		= $(addprefix $(INCS_DIR)/, MutantStack.hpp)
 
-# Compiler, flags and shortcuts
-CC		=	c++
-CX		=	.cpp
-RM		=	rm -rf
-CPY		=	cp -f
-MKDR	=	mkdir -p
-INCLUDE =	-I include
+MAIN_INC	= -I$(INCS_DIR)
 
-# Creates file paths
-SRCS	=	$(addprefix $(SRCDIR), $(addsuffix $(CX), $(FILES)))
-OBJS	=	$(addprefix $(OBJDIR), $(addsuffix .o, $(FILES)))
+$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.cpp
+	@echo "Creating directory: $(OBJS_DIR)"
+	@mkdir -p $(OBJS_DIR) || echo "Failed to create directory: $(OBJS_DIR)"
+	${CXX} ${CXXFLAGS} ${MAIN_INC} -c $< -o $@
 
-# Command to call when using make run or make leaks
-CMD		=	./$(NAME) $(ARGS)
+all			: $(NAME)
 
+$(NAME)		: $(OBJS) $(INCS)
+	$(CXX) $(CXXFLAGS) $(OBJS) $(MAIN_INC) -o $(NAME)
 
-#------------------------------------------------------------------------------#
-#                                 BASE TARGETS                                 #
-#------------------------------------------------------------------------------#
+clean		:
+			@$(RM) $(OBJS)
+			@rmdir $(OBJS_DIR) 2>/dev/null || true
 
-# For full install (except brew)
-long: cmake glfw $(NAME)
+fclean		: clean
+			@$(RM) $(NAME)
 
-# For standard compilation
-all: $(NAME)
+re			: fclean all
 
-# Compiles all files into an executable
-$(NAME): $(OBJS)
-	@echo "$(GREEN)\nFiles compiled with flags : $(CFLAGS)\n $(DEFCOL)"
-	$(HIDE) $(CC) $(MODE) $(CFLAGS) -o $@ $^ $(INCLUDE) $(LIBS) $(LIBX)
-	@echo "$(CYAN)Executable created !\n $(DEFCOL)"
+run			: re
+			@$(RM) $(OBJS)
+			@./$(NAME) 0
+leaks		: re
+			@$(RM) $(OBJS)
+			valgrind --leak-check=full ./$(NAME)
 
-# Compiles each source file into a .o file
-$(OBJS): $(OBJDIR)%.o : $(SRCDIR)%$(CX)
-	@echo "$(YELLOW)Compiling file : $< $(DEFCOL)"
-	$(HIDE) $(CC) $(MODE) $(CFLAGS) -c $< -o $@
+runall		:
+			make run;
+			cd ../ex01/; make run;
+			cd ../ex02/; make run;			
+			cd ../ex03/; make run;
+			cd ../ex00/;
 
+leaksall	:
+			make leaks;
+			cd ../ex01/; make leaks;
+			cd ../ex02/; make leaks;			
+			cd ../ex03/; make leaks;
+			cd ../ex00/;
 
-#------------------------------------------------------------------------------#
-#                               CLEANING TARGETS                               #
-#------------------------------------------------------------------------------#
-
-# Removes objects
-clear: clean
-clean:
-	$(HIDE) $(RM) $(OBJS)
-	$(HIDE) $(RM) $(NAME).dSYM
-	@echo "$(MAGENTA)\nDeleted object files\n $(DEFCOL)"
-
-# Removes object dir and executable
-fclear: fclean
-fclean: clean
-	$(HIDE) $(RM) $(OBJDIR)
-	@echo "$(RED)Deleted object directory\n $(DEFCOL)"
-	$(HIDE) $(RM) $(NAME)
-	@echo "$(RED)Deleted executable\n $(DEFCOL)"
-
-# Removes object dir and executable and remakes everything
-re: fclean all
-	@echo "$(CYAN)Rebuilt everything !\n $(DEFCOL)"
-
-
-#------------------------------------------------------------------------------#
-#                               SHORTCUT TARGETS                               #
-#------------------------------------------------------------------------------#
-
-# Runs the program
-rerun: re run
-run: all
-	@echo "$(YELLOW)Launching command : $(CMD) $(DEFCOL)"
-	@echo "$(GREEN)"
-	$(HIDE) $(CMD); \
-	if [ $$? -eq 0 ]; then \
-		echo "$(GREEN)\nExited normally\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\nExited with error code $$?\n $(DEFCOL)"; \
-	fi
-	$(HIDE) $(MAKE) clean
-
-# Runs the program with leaks
-releaks: re leaks
-leaks: all
-	@echo "$(RED)Launching command : leaks $(LFLAGS) -- $(CMD) $(DEFCOL)"
-	@echo "$(YELLOW)"
-	$(HIDE) leaks $(LFLAGS) -- $(CMD); \
-	if [ $$? -eq 0 ]; then \
-		echo "$(GREEN)\nExited normally\n $(DEFCOL)"; \
-		echo "$(GREEN)No leaks found...\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\nExited with error code $$?\n $(DEFCOL)"; \
-		echo "$(RED)! LEAKS FOUND !\n $(DEFCOL)"; \
-	fi
-	$(HIDE) $(MAKE) clean
-
-# Runs the program with valgrind
-revleaks: re vleaks
-vleaks: all
-	@echo "$(RED)Launching command : valgrind $(VFLAGS) $(CMD) $(DEFCOL)"
-	@echo "$(YELLOW)"
-	$(HIDE) valgrind $(VFLAGS) $(CMD); \
-	if [ $$? -eq 0 ]; then \
-		echo "$(GREEN)\nExited normally\n $(DEFCOL)"; \
-		echo "$(GREEN)No leaks found...\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\nExited with error code $$? $(DEFCOL)"; \
-		echo "$(RED)! LEAKS FOUND !\n $(DEFCOL)"; \
-	fi
-	$(HIDE) $(MAKE) clean
-
-# Runs the norminette
-norm:
-	@echo "$(DEFCOL)"
-	@echo "$(YELLOW)Norminetting $(CX) files $(RED)"
-	@norminette $(SRCS) | grep Error || true
-	@echo "$(DEFCOL)"
-	@echo "$(YELLOW)Norminetting .hpp files $(RED)"
-	@norminette include | grep Error || true
-	@echo "$(DEFCOL)"
-
-# Updates the git submodules
-sub:
-	@echo "$(YELLOW)Updating submodules \n $(WHITE)"
-	$(HIDE) git submodule update --init --recursive
-	@echo "$(GREEN)Submodules updated ! \n $(DEFCOL)"
-
-# Updates the libft module (requires push after)
-libft:
-	@echo "$(YELLOW)Updating libft to latest commit $(WHITE)"
-	$(HIDE) cd Libft42 ; git pull origin main
-	@echo "$(GREEN)Libft updated ! \n$(DEFCOL)"
-
-
-#------------------------------------------------------------------------------#
-#                                 BREW TARGETS                                 #
-#------------------------------------------------------------------------------#
-
-# Installs/Updates homebrew (called manually cause slow af)
-brew:
-	@echo "$(YELLOW)\nInstalling Brew $(DEFCOL)"
-	$(HIDE) bash include/brew_install.sh; \
-	if [ $$? -eq 0 ]; then \
-		echo "$(BLUE)\nBrew installed ! $(DEFCOL)"; \
-		echo "$(RED)\n! CLOSE AND REOPEN TERMINAL !\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\n! FAILED TO INSTALL BREW !\n $(DEFCOL)"; \
-	fi
-
-# Installs/Updates cmake
-cmake:
-	@echo "$(YELLOW)\nInstalling Cmake $(DEFCOL)"
-	$(HIDE) brew install cmake; \
-	if [ $$? -eq 0 ]; then \
-		echo "$(BLUE)\nCmake installed !\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\n! FAILED TO INSTALL CMAKE !\n $(DEFCOL)"; \
-	fi
-
-# Installs/Updates valgrind
-grind:
-	@echo "$(YELLOW)\nInstalling Valgrind $(DEFCOL)"
-	$(HIDE) brew tap LouisBrunner/valgrind
-	$(HIDE) brew install --HEAD LouisBrunner/valgrind/valgrind; \
-	if [ $$? -eq 0 ]; then \
-		echo "$(BLUE)\nVALGRIND installed !\n $(DEFCOL)"; \
-	else \
-		echo "$(RED)\n! FAILED TO INSTALL VALGRIND !\n $(DEFCOL)"; \
-	fi
+fcleanall	:
+			make fclean;
+			cd ../ex01/; make fclean;
+			cd ../ex02/; make fclean;			
+			cd ../ex03/; make fclean;
+			cd ../ex00/;
+			
+.PHONY		: all clean fclean re run leaks leaksall fcleanall runall
